extends:
  - "@commitlint/config-conventional"
rules:
  # prevent commit if "type(scope?): subject" not in lowercase
  type-case:
    - 2
    - always
    - lower-case
  scope-case:
    - 2
    - always
    - lower-case